name: CI

on: [push, pull_request]

jobs:
  CI:
    timeout-minutes: 10
    name: >-
      CI ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos ]
        ruby: [ 2.7, 2.6, 2.5 ]
    steps:
      - uses: actions/checkout@v2
      - name: load Ruby and dependencies
        uses: MSP-Greg/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: install
        run:  bundle install --jobs 4 --retry 3
      - name: test
        run:  bundle exec rake test

  Win:
    timeout-minutes: 10
    name: >-
      CI ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows ]
        ruby: [ 2.7, 2.6, 2.5]
    steps:
      - uses: actions/checkout@v2
      - name: load Ruby and sqlite3
        uses: MSP-Greg/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: install
        run:  bundle install --jobs 4 --retry 3
      - name: test
        run:  bundle exec rake test
